# Generated by Django 5.0.4 on 2024-05-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_hotelimages_hotel_remove_hotel_room_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
