# Generated by Django 5.0.4 on 2024-05-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hotel_image_room_amenities_alter_hotel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='value',
            field=models.CharField(choices=[('1', 'Still'), ('0', 'Out of room')], default='1', max_length=10),
        ),
    ]
