# Generated by Django 5.0.4 on 2024-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_room_hotel_remove_room_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
