# Generated by Django 5.0.4 on 2024-05-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_room_room_type_alter_room_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='value',
            new_name='room_status',
        ),
    ]
