# Generated by Django 5.0.4 on 2024-05-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='evaluate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='room_count',
            field=models.IntegerField(default=1),
        ),
    ]
