# Generated by Django 5.0.4 on 2024-05-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_uid_amenities_id_rename_uid_hotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='evaluate',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_img'),
        ),
    ]
