# Generated by Django 5.0.6 on 2024-05-23 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_room_evaluate_alter_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='roomimages',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roomimages',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='num_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('cash', 'Cash')], default='cash', max_length=255),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='home.room'),
        ),
    ]
